CREATE TABLE MARKET_LISTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MONTH NUMBER(2, 0) NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
    YEAR NUMBER(4, 0) NOT NULL CHECK (YEAR > 2024)
);
