CREATE TABLE MARKET_LIST_ITEMS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIST_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR2(255) NOT NULL,
    QUANTITY NUMBER,
    CHECKED NUMBER(1, 0) DEFAULT 0,
    CONSTRAINT FK_LIST_ID FOREIGN KEY (LIST_ID) REFERENCES MARKET_LISTS (ID)
);
